from __future__ import annotations

from typing import Any

APP_SCHEMA_PREFIX = "garmin-claws.v1"

METRIC_DEFINITIONS: dict[str, dict[str, Any]] = {
    "training_readiness": {
        "id": "training_readiness",
        "name": "Training Readiness",
        "plain_english": "Garmin's 0-100 estimate of how prepared the body is to handle training today.",
        "best_used_for": ["daily training gate", "maximum intensity selection", "recovery context"],
        "do_not_overinterpret": ["It cannot see muscular soreness or mental fatigue.", "It is not a workout prescription by itself."],
        "interpretation_rules": ["Use as a readiness gate, then use load focus to choose workout type.", "Garmin bases it on sleep score, recovery time, HRV status, acute load, sleep history, and stress history."],
        "flow_usage": ["trainability", "daily-coach", "recovery-check"],
    },
    "hrv_status": {
        "id": "hrv_status",
        "name": "HRV Status",
        "plain_english": "A trend-based recovery signal derived from overnight heart-rate variability.",
        "best_used_for": ["recovery trend", "fatigue detection", "illness or stress warning"],
        "do_not_overinterpret": ["Do not compare absolute HRV values between people.", "Do not overreact to one night."],
        "interpretation_rules": ["Compare against the user's personal baseline, not a population norm.", "Balanced usually supports training; low or unbalanced can reflect stress, illness, alcohol, dehydration, poor sleep, or training fatigue."],
        "flow_usage": ["recovery-check", "trainability", "illness-check"],
    },
    "load_focus": {
        "id": "load_focus",
        "name": "Training Load Focus",
        "plain_english": "Distribution of recent training load across low aerobic, high aerobic, and anaerobic buckets.",
        "best_used_for": ["workout type selection", "finding missing training stimulus", "weekly planning"],
        "do_not_overinterpret": ["It requires enough recent training history.", "It should be gated by recovery before adding intensity."],
        "interpretation_rules": ["Low aerobic supports base and recovery.", "High aerobic improves lactate threshold, VO2 max, and endurance.", "Anaerobic improves speed and anaerobic capacity but needs low-aerobic balance."],
        "flow_usage": ["load-diagnosis", "trainability", "daily-coach", "weekly-review"],
    },
    "sleep_score": {
        "id": "sleep_score",
        "name": "Sleep Score",
        "plain_english": "Garmin's composite score for last night's sleep quality and quantity.",
        "best_used_for": ["overnight recovery context", "training readiness interpretation"],
        "do_not_overinterpret": ["Duration alone is not recovery.", "Sleep score should be interpreted with HRV, overnight HR, stress, and Body Battery recharge."],
        "interpretation_rules": ["Use sleep as one contributor to training decisions, not the whole decision."],
        "flow_usage": ["sleep-recovery", "trainability", "daily-coach"],
    },
    "body_battery": {
        "id": "body_battery",
        "name": "Body Battery",
        "plain_english": "Garmin's estimate of general energy reserve based on sleep, stress, rest, and activity.",
        "best_used_for": ["daily pacing", "general energy", "non-sport fatigue context"],
        "do_not_overinterpret": ["It is less sport-specific than Training Readiness."],
        "interpretation_rules": ["Use for pacing work and life load; use Training Readiness and load focus for workouts."],
        "flow_usage": ["daily-coach", "energy-status"],
    },
    "acute_load": {
        "id": "acute_load",
        "name": "Acute Load",
        "plain_english": "Recent workout-induced training stress, usually interpreted over about a week.",
        "best_used_for": ["underload or overload detection", "ramp-rate context"],
        "do_not_overinterpret": ["It does not directly specify which workout type to do."],
        "interpretation_rules": ["Pair with chronic load/ACWR and readiness to avoid ramping too quickly."],
        "flow_usage": ["trainability", "weekly-review"],
    },
}

CAPABILITIES = [
    {
        "name": "daily summary",
        "description": "Fetch normalized daily Garmin metrics for one date.",
        "requires_auth": True,
        "safe": True,
        "read_only": True,
        "output_schema": f"{APP_SCHEMA_PREFIX}.daily_summary",
    },
    {
        "name": "sleep summary",
        "description": "Fetch normalized sleep metrics for one date.",
        "requires_auth": True,
        "safe": True,
        "read_only": True,
        "output_schema": f"{APP_SCHEMA_PREFIX}.sleep_summary",
    },
    {
        "name": "activity recent",
        "description": "Fetch normalized recent activities with limit/start pagination.",
        "requires_auth": True,
        "safe": True,
        "read_only": True,
        "output_schema": f"{APP_SCHEMA_PREFIX}.activity_list",
    },
    {
        "name": "metrics explain",
        "description": "Return agent-facing definitions and interpretation rules for Garmin metrics.",
        "requires_auth": False,
        "safe": True,
        "read_only": True,
        "output_schema": f"{APP_SCHEMA_PREFIX}.metric_definition",
    },
    {
        "name": "health status",
        "description": "Interpret core overnight health metrics against personal ranges.",
        "requires_auth": True,
        "safe": True,
        "read_only": True,
        "output_schema": f"{APP_SCHEMA_PREFIX}.health_status",
    },
    {
        "name": "sleep recovery",
        "description": "Interpret whether last night's sleep supports training.",
        "requires_auth": True,
        "safe": True,
        "read_only": True,
        "output_schema": f"{APP_SCHEMA_PREFIX}.sleep_recovery",
    },
    {
        "name": "training load-balance",
        "description": "Diagnose low/high aerobic and anaerobic load gaps.",
        "requires_auth": True,
        "safe": True,
        "read_only": True,
        "output_schema": f"{APP_SCHEMA_PREFIX}.training_load_balance",
    },
    {
        "name": "flow plan",
        "description": "Describe an agent workflow without calling Garmin.",
        "requires_auth": False,
        "safe": True,
        "read_only": True,
        "output_schema": f"{APP_SCHEMA_PREFIX}.flow_plan",
    },
    {
        "name": "flow run daily-coach",
        "description": "Run the composite daily coaching flow for health, sleep, readiness, load, and recommendation.",
        "requires_auth": True,
        "safe": True,
        "read_only": True,
        "output_schema": f"{APP_SCHEMA_PREFIX}.daily_coach",
    },
    {
        "name": "schema show",
        "description": "Return a JSON schema embedded in garmin-claws.",
        "requires_auth": False,
        "safe": True,
        "read_only": True,
        "output_schema": f"{APP_SCHEMA_PREFIX}.schema",
    },
]

SCHEMAS: dict[str, dict[str, Any]] = {
    "daily_summary": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://iamjameskeane.github.io/garmin-claws/schemas/daily_summary.v1.json",
        "type": "object",
        "required": ["ok", "schema_version", "data", "warnings", "meta"],
        "properties": {
            "ok": {"const": True},
            "schema_version": {"const": "garmin-claws.v1.daily_summary"},
            "data": {"type": "object"},
            "warnings": {"type": "array", "items": {"type": "string"}},
            "meta": {"type": "object"},
        },
    },
    "sleep_summary": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://iamjameskeane.github.io/garmin-claws/schemas/sleep_summary.v1.json",
        "type": "object",
        "properties": {"schema_version": {"const": "garmin-claws.v1.sleep_summary"}},
    },
    "activity_list": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://iamjameskeane.github.io/garmin-claws/schemas/activity_list.v1.json",
        "type": "object",
        "properties": {"schema_version": {"const": "garmin-claws.v1.activity_list"}},
    },
    "error": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://iamjameskeane.github.io/garmin-claws/schemas/error.v1.json",
        "type": "object",
        "properties": {"schema_version": {"const": "garmin-claws.v1.error"}},
    },
    "metric_definition": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://iamjameskeane.github.io/garmin-claws/schemas/metric_definition.v1.json",
        "type": "object",
        "properties": {"schema_version": {"const": "garmin-claws.v1.metric_definition"}},
    },
    "health_status": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://iamjameskeane.github.io/garmin-claws/schemas/health_status.v1.json",
        "type": "object",
        "properties": {"schema_version": {"const": "garmin-claws.v1.health_status"}},
    },
    "sleep_recovery": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://iamjameskeane.github.io/garmin-claws/schemas/sleep_recovery.v1.json",
        "type": "object",
        "properties": {"schema_version": {"const": "garmin-claws.v1.sleep_recovery"}},
    },
    "training_load_balance": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://iamjameskeane.github.io/garmin-claws/schemas/training_load_balance.v1.json",
        "type": "object",
        "properties": {"schema_version": {"const": "garmin-claws.v1.training_load_balance"}},
    },
    "trainability": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://iamjameskeane.github.io/garmin-claws/schemas/trainability.v1.json",
        "type": "object",
        "properties": {"schema_version": {"const": "garmin-claws.v1.trainability"}},
    },
    "daily_coach": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://iamjameskeane.github.io/garmin-claws/schemas/daily_coach.v1.json",
        "type": "object",
        "properties": {"schema_version": {"const": "garmin-claws.v1.daily_coach"}},
    },
}
